version: '3.7'
services:
    web:
        build:
            context: .
            dockerfile: ./compose/local/Dockerfile
        command: /start
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
    redis:
        image: redis:latest
    db:
        image: postgres:11
        
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

        volumes:
            - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data: