version: '3.7'
services:
    web:
        build:
            context: .
            dockerfile: ./compose/local/Dockerfile
        command: /start
        volumes:
            - .:/code
        ports:
            - 8000:8000
    redis:
        image: redis:latest