version: '3.3'
services:
    web:
        build:
            context: .
            dockerfile: ./compose/local/Dockerfile
        command: gunicorn chat_app.wsgi:application --bind 0.0.0.0:8000
        depends_on:
            - redis
        volumes:
            - .:/code
        expose:
            - 8000
    nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        ports:
            - 1337:80
        depends_on:
            - web
    redis:
        image: redis:latest